package main

import (
	"fmt"
	"os"
	"unicode"
	"unicode/utf8"
)

func main() {
	output := fileHeaderTemplate
	output += "// ELEMENTS\n"
	for _, name := range elements {
		output += generateElement(name)
	}
	output += "\n// VOID ELEMENTS\n"
	for _, name := range voidElements {
		output += generateVoidElement(name)
	}

	os.WriteFile("generated_elements.go", []byte(output), 0644)

}

var fileHeaderTemplate = `// Code generated by ./cmd/generator. generator.go. DO NOT EDIT.

package jj

`

var elementTemplate = `

func (j *J) %s(attrs Attributes, f func()) {
	j.Element("%s", attrs, f)
}
`

func generateElement(name string) string {
	return fmt.Sprintf(elementTemplate, uppercaseFirst(name), name)
}

var voidElementTemplate = `

func (j *J) %s(attrs Attributes) {
	j.Element("%s", attrs, nil)
}
`

func generateVoidElement(name string) string {
	return fmt.Sprintf(voidElementTemplate, uppercaseFirst(name), name)
}

func uppercaseFirst(s string) string {
	if s == "" {
		return s
	}

	r, n := utf8.DecodeRuneInString(s)
	return string(unicode.ToUpper(r)) + s[n:]
}

var elements = []string{
	"a",
	"abbr",
	"address",
	"article",
	"aside",
	"audio",
	"b",
	"bdi",
	"bdo",
	"blockquote",
	"body",
	"button",
	"canvas",
	"caption",
	"cite",
	"code",
	"colgroup",
	"datalist",
	"dd",
	"del",
	"details",
	"dfn",
	"div",
	"dl",
	"dt",
	"em",
	"fieldset",
	"figcaption",
	"figure",
	"footer",
	"form",
	"h1",
	"h2",
	"h3",
	"h4",
	"h5",
	"h6",
	"head",
	"header",
	"hgroup",
	"html",
	"i",
	"iframe",
	"ins",
	"kbd",
	"label",
	"legend",
	"li",
	"main",
	"map",
	"mark",
	"menu",
	"meter",
	"nav",
	"noscript",
	"object",
	"ol",
	"optgroup",
	"option",
	"output",
	"p",
	"pre",
	"progress",
	"q",
	"rp",
	"rt",
	"ruby",
	"s",
	"samp",
	"script",
	"section",
	"select",
	"small",
	"span",
	"strong",
	"style",
	"sub",
	"summary",
	"sup",
	"table",
	"tbody",
	"td",
	"textarea",
	"tfoot",
	"th",
	"thead",
	"time",
	"title",
	"tr",
	"ul",
	"var",
	"video",
}

var voidElements = []string{
	"area",
	"base",
	"br",
	"col",
	"command",
	"embed",
	"hr",
	"img",
	"input",
	"keygen",
	"link",
	"meta",
	"param",
	"source",
	"track",
	"wbr",
}
